services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no test"

script:
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag reverseproxy thangth8/reverseproxy:v1
  - docker tag udagram-api-user thangth8/udagram-api-user:v1
  - docker tag udagram-api-feed thangth8/udagram-api-feed:v1
  - docker tag udagram-frontend thangth8/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thangth8/reverseproxy:v1
  - docker push thangth8/udagram-api-user:v1
  - docker push thangth8/udagram-api-feed:v1
  - docker push thangth8/udagram-frontend:v1
