services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sudkul/udagram-api-user:v1
